version: '3.9'
services:
  mysql-kc:
    image: mysql:latest
    ports:
      - 3307:3306
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: keycloak_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak-w:
    image: quay.io/keycloak/keycloak:22.0.4
    command: start-dev
    ports:
      - 9081:8080
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_USER: keycloak
      DB_PASSWORD: root
      DB_ADDR: mysql-kc
      DB_PORT: 3307
      DB_DATABASE: keycloak_db
      DB_VENDOR: MYSQL
      DB_SCHEMA: public
    depends_on:
      - mysql-kc
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:
    driver: bridge

volumes:
  keycloak-and-mysql-volume:
